modLoader = "javafml"
loaderVersion = "[40,)"
license = "ALL License"
issueTrackerURL = "https://github.com/Mrthomas20121/ThermalExtra/issues"

[[mods]]
modId = "crystal_augment"
version = "0.0.1-1.20.1"
displayName = "Crystal Augment"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/thermal_extra"
#logoFile="tinkers_reforged_logo.png"
credits = "Team CoFH"
authors = "fish_dan"
description = '''
Add more augments to Thermal
'''

[[dependencies.crystal_augment]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,)"
    ordering = "NONE"
    side = "BOTH"